/**
 * 
 */
package org.eclipse.scout.shared.scrolling;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class SecondFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public SecondFormData() {
  }

  /**
   * access method for property SecondNr.
   */
  public Long getSecondNr() {
    return getSecondNrProperty().getValue();
  }

  /**
   * access method for property SecondNr.
   */
  public void setSecondNr(Long secondNr) {
    getSecondNrProperty().setValue(secondNr);
  }

  public SecondNrProperty getSecondNrProperty() {
    return getPropertyByClass(SecondNrProperty.class);
  }

  public TreeBox getTreeBox() {
    return getFieldByClass(TreeBox.class);
  }

  public static class SecondNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;

    public SecondNrProperty() {
    }
  }

  public static class TreeBox extends AbstractValueFieldData<Long[]> {

    private static final long serialVersionUID = 1L;

    public TreeBox() {
    }
  }
}
