/**
 * 
 */
package validation.shared.error.services;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;

import validation.shared.error.AbstractListBoxGroupBoxData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class DesktopFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public DesktopFormData() {
  }

  public MyListBoxTest getMyListBoxTest() {
    return getFieldByClass(MyListBoxTest.class);
  }

  public static class MyListBoxTest extends AbstractListBoxGroupBoxData {

    private static final long serialVersionUID = 1L;

    public MyListBoxTest() {
    }
  }
}
