/**
 * 
 */
package validation.shared.error;

import java.util.Map;
import java.util.Set;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class AbstractListBoxGroupBoxData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public AbstractListBoxGroupBoxData() {
  }

  public Constraint2 getConstraint2() {
    return getFieldByClass(Constraint2.class);
  }

  public ListBoxTest getListBoxTest() {
    return getFieldByClass(ListBoxTest.class);
  }

  public static class Constraint2 extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Constraint2() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class ListBoxTest extends AbstractValueFieldData<Set<Long>> {

    private static final long serialVersionUID = 1L;

    public ListBoxTest() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.LOOKUP_CALL, CompanyTypeLookupCall.class);
      ruleMap.put(ValidationRule.MASTER_VALUE_FIELD, Constraint2.class);
    }
  }
}
